### ISSUE TITLE
Smoothly works on Chrome, but not works on Safari

### ISSUE THREAD

**Issue by JoeJoeLiu** [E011011101001/Twitter-Block-With-Love#1]
The Tampermonkey displays the script is enabled and working on, but there's no button on the likers' page.
Mac OS version: 10.15.4
Tampermonkey version: 4.10.6108 (from Mac App Store)

**Comment by JoeJoeLiu** [comment]
It also not works on Firefox with same situation.

**Comment by E011011101001** [comment]
It works with Greasemonkey on Firefox 74.0, macOS Catalina 10.15.3.
However, using the same browser and OS with Tampermonkey, I could not even alert or log anything on the console. I'm trying to figure out what the problem is.

For now, you can just use Chrome or use Greasemonkey with Firefox on macOS.

**Comment by JoeJoeLiu** [comment]
Yes, that's a weird issue, and I just confirmed it's worked with Greasemonkey. Anyway, thank you for your time and your life-saving script.

**Comment by E011011101001** [comment]
Thanks XD

**Comment by E011011101001** [comment]
It turns out that this problem is caused by some CSP policies on Twitter. Tampermonkey just does not work on Twitter with Firefox.
So in all, if you want to use this userscript on Firefox, you'd better choose Greasemonkey instead of Tampermonkey. But if you do insist on Tampermonkey with Firefox, you have to turn  `security.csp.enalbe` to false to make it work on Twitter.
You can refer to this [comment](https://github.com/Tampermonkey/tampermonkey/issues/700#issuecomment-530685051) for details.

**Comment by E011011101001** [comment]
Finally! Tampermonkey's update v4.11.6114 fixed this problem!
Now you can keep `csp` `true` by default and use Tampermonkey at twitter.com~
